# In this file the configuration for
# the data preprocessing is defined

dataset_config:
    # configuration name
    name: ES_5t_regime_2015-01_to_2021-06_ema_group_w8
    
    # main dataset
    market_file: split_ES_minute_5T_dwn_smpl_2015-01_to_2021-06_g8week_r15
    macd_vars: ['ESc']
    rsi_vars: ['ESc']
    macd_periods: [24, 12, 6]
    returns_vars: ['ESc', 'ESh', 'ESo', 'ESl']
    returns_from_ema: (11, True)
    true_target: ESc_e11
    
    # regime file (if any)
    regime_file: regime_ESc_r_T10Y2Y_VIX
    
    # aditional dataset (if any)
    additional_file: subset_NQ_minute_5T_dwn_smpl_2012-01_to_2021-07
    additional_prefix_col: NQ
    additional_macd_vars: ['NQc']
    additional_returns_vars: ['NQc', 'NQh', 'NQo', 'NQl']
    